### ISSUE TITLE
ValueError: PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by arkonbob** [arminstraub/krop#24]
Whenever I try to run either the Ubuntu Universe packaged version of the app or the snap version in Lubuntu 19.10, I receive the following error:

`ValueError: PyCapsule_GetPointer called with incorrect name`

The error described here:

[https://github.com/leo-editor/leo-editor/issues/1106](url)

... was similar, so I tried applying the fix there to the latest code from the git repo (without a full understanding of the issue). I have added the following to vieweritem.py at line 25:

`    except ValueError:
        QtWebKitWidgets = None`

I then ran:

```
python3 setup.py build
sudo python3 setup.py install
```

Krop now runs for me.

**Comment by arkonbob** [comment]
Spoke too soon... Krop runs but it seems there are still issues with the Poppler library, so I can't actually open any PDFs.

**Comment by arminstraub** [comment]
Thank you for bringing this up!  Since the command
`from popplerqt5 import Poppler`
is what causes that error for you this means that, as you observed, the Poppler library on your system has an issue.  Your workaround works to start krop but it doesn't solve the underlying issue because Poppler is required for krop to do its work.

Fortunately, you should be able to upgrade that library: at least Ubuntu 20.04 does not appear to have the issue you describe (I have just setup a Kubuntu 20.04 system and installed krop successfully; however, because of another issue, this requires using the current krop code from github or waiting for the 0.5.2 release which I hope to complete soon).
