### ISSUE TITLE
Krop "refuses" to save

### ISSUE THREAD

**Issue by kwetal** [arminstraub/krop#34]
Started Krop and followed instructions as per the "Help" menu tab: open pdf file, create selection: ok.
Buttons Zoom, Previous, Next and Trim all work as expected.
Clicked the _Krop!_ button [smiling face :-)] and expected a File Save Dialog to save the cropped pdf, but nothing happened.
Tried different distributions (Snap, Flatpak and Apt): no difference (except that the Apt-version is rather old).
Also started krop from the command line to view possible error messages but nothing shows when pressing the _Krop!_ button.
Any tips welcome!

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```

**Comment by arminstraub** [comment]
If there is no error message then, after pressing "Krop!" you should have a cropped version of your file in your filesystem.  By default, it has the same name as the opened file but ending with "-cropped.pdf" instead.  For a File Save Dialog, click on the little folder icon in "Save cropped PDF to".  (My apologies for the long silence due to too little time.)
