### ISSUE TITLE
PyPDF2 usage: New syntax / deprecations and the dependency

### ISSUE THREAD

**Issue by MartinThoma** [arminstraub/krop#35]
Hi!

I've noticed that krop uses PyPDF2. Is there a reason for not putting it in the setup.py as a dependency?

PyPDF2 has changed a lot since April. We try hard not to break stuff (see [deprecation process](https://pypdf2.readthedocs.io/en/latest/dev/deprecations.html)), but we also want to move forward. As we modernized the API, a lot of the names changed. It's mostly switching from camelCase to snake_case, but see [CHANGELOG](https://pypdf2.readthedocs.io/en/latest/meta/CHANGELOG.html) "deprecation" for details.

**Comment by MartinThoma** [comment]
Especially under 1.28.0: https://pypdf2.readthedocs.io/en/latest/meta/CHANGELOG.html#id40

**Comment by MartinThoma** [comment]
I became the maintainer of `pypdf` as well and migrated the `PyPDF2` project into `pypdf` (now all lowercase).

However, it seems to me that krop is dead.

**Comment by arminstraub** [comment]
Thank you, Martin!  It is fantastic to see pypdf so alive again :)  My apologies for the horribly long silence due to too little time.

I have just added support for pypdf and the new naming scheme.  pyPdf and PyPDF2 are also still supported.  (The only non-supported option is PyPDF2 with the new naming scheme, which I believe only existed for a brief moment of time; if anybody desperately needs that supported as well, this could certainly be done easily.)

I will soon adjust the documentation and installation guidelines.

PS: I'll have to think about the dependency question. I'm leaning against it since krop can run (but not crop) without pypdf.  Now pikepdf is an alternative option as well and more might be added. (In the past, I liked having the option of having the various needed Python packages installable from a variety of sources as well as installable after the fact.)
